alter table EPAY.ONLINESUBTRANS add column MERNBR	VARCHAR(128);

alter table ODSHIS.EPAY_ONLINESUBTRANS add column MERNBR	VARCHAR(128);

REORG TABLE EPAY.ONLINESUBTRANS;

REORG TABLE ODSHIS.EPAY_ONLINESUBTRANS;

