--property change
alter table DELTA.IMBS_T_SIGN_CKSY alter column ACT_NAME set data type CHARACTER(60);
alter table IMBS.T_SIGN_CKSY alter column ACT_NAME set data type CHARACTER(60);
alter table ODSHIS.IMBS_T_SIGN_CKSY alter column ACT_NAME set data type CHARACTER(60);
REORG TABLE IMBS.T_SIGN_CKSY;

REORG TABLE ODSHIS.IMBS_T_SIGN_CKSY;

REORG TABLE DELTA.IMBS_T_SIGN_CKSY;

--rename table
rename table IMBS.T_SIGN_CKSY_HIST to T_SIGN_CKSY_HIST_20150325
rename table ODSHIS.IMBS_T_SIGN_CKSY_HIST to IMBS_T_SIGN_CKSY_HIST_20150325
--rename table
rename table IMBS.T_SIGN_CKSY_HIST to T_SIGN_CKSY_HIST_20150325
rename table ODSHIS.IMBS_T_SIGN_CKSY_HIST to IMBS_T_SIGN_CKSY_HIST_20150325
